import { describe, it, expect } from 'vitest';
import postcss from 'postcss';
import type { Plugin } from 'postcss';
import postcssHtml from 'postcss-html';
import plugin from '../src';

describe('postcss-html pipeline (Vue SFC / HTML <style> blocks)', () => {
  const html = `<html><head>
<style>.hero { height: 100dvh; }</style>
<style>.panel { width: calc(100dvw - 40px); }</style>
</head><body></body></html>`;

  it('transforms every style block in a Document', async () => {
    const result = await postcss([plugin()]).process(html, {
      from: 'page.html',
      syntax: postcssHtml(),
    });
    expect(result.content).toContain('height: 100vh');
    expect(result.content).toContain('height: 100dvh');
    expect(result.content).toContain('calc(100vw - 40px)');
  });

  it('css-var strategy injects one page-global seed covering all blocks', async () => {
    const result = await postcss([plugin({ strategy: 'css-var' })]).process(html, {
      from: 'page.html',
      syntax: postcssHtml(),
    });
    expect(result.content).toContain('calc(var(--pvf-dvh, 1vh) * 100)');
    expect(result.content).toContain('calc(var(--pvf-dvw, 1vw) * 100)');
    expect(
      (result.content.match(/:root \{ --pvf-dvh: 1vh; --pvf-dvw: 1vw \}/g) ?? []).length,
    ).toBe(1);
    expect((result.content.match(/postcss-viewport-fallback: disable/g) ?? []).length).toBe(1);
    expect(result.content).toContain('@supports (height: 1dvh)');
    expect(result.content).toContain('@supports (height: 1dvw)');
  });
});

describe('utility-generator pipeline (Tailwind-like: units appear mid-build)', () => {
  const generator: Plugin = {
    postcssPlugin: 'fake-utility-generator',
    Once(root) {
      root.walkAtRules('utilities', (atRule) => {
        atRule.replaceWith(
          `.h-dvh { height: 100dvh }\n.min-h-dvh { min-height: 100dvh }\n.w-dvw { width: 100dvw }`,
        );
      });
    },
  };

  it('transforms utilities generated by an earlier plugin in the same pipeline', async () => {
    const result = await postcss([generator, plugin()]).process(`@utilities;`, {
      from: undefined,
    });
    expect(result.css).toContain('.h-dvh { height: 100vh; height: 100dvh }');
    expect(result.css).toContain('.min-h-dvh { min-height: 100vh; min-height: 100dvh }');
    expect(result.css).toContain('.w-dvw { width: 100vw; width: 100dvw }');
  });

  it('documents why fastSkip must stay off for generator pipelines', async () => {
    const result = await postcss([generator, plugin({ fastSkip: true })]).process(
      `@utilities;`,
      { from: undefined },
    );
    expect(result.css).not.toContain('height: 100vh');
  });
});

describe('template-literal CSS-in-JS extraction', () => {
  it('transforms values inside extracted styled-components CSS', async () => {
    const css = `height: 100dvh;\nwidth: 50dvw;`;
    const result = await postcss([plugin()]).process(css, { from: undefined });
    expect(result.css).toContain('height: 100vh');
    expect(result.css).toContain('width: 50vw');
  });
});
